#include "main.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/Board.h"
#include "images/BunnyLeft.h"
#include "images/BunnyRight.h"
#include "images/MoveLeft.h"
#include "images/MoveRight.h"
#include "images/SitLeft.h"
#include "images/SitRight.h"
#include "images/Carrot.h"
#include "images/Start.h"
#include "images/Time.h"
/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  DRAWSTART,
  DRAWPLAY,
  DRAWBUNNY,
  DRAWCARROT,
  RESTART,
  PLAY,
  TIMEOUTDRAW,
  TIMEOUT,
};
void addCarrots(int start, int carrotCount);
// All the info for the current state of the game
struct state {
  enum gba_state gamestate;
  int numcarrotsonBoard;
  int collected_carrots;
  char collectedcarrotsNum [3];
  struct carrot carrots_collected [8];
  int gameStart;
  int animation;
};

// Important Instances
struct state cs;
struct bunny bunny;
struct bunny potentialBunny;
struct animationBunny animationBunny;
struct bush bush[24];
struct carrot carrots[8];
volatile u16 colors[5] = {BUSHGREEN, BUSHGREENHIGH, OLIVE, DARKGREEN, TEAL};


int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  //enum gba_state state = DRAWSTART;
  cs.gamestate = DRAWSTART;
  cs.numcarrotsonBoard = 0;
  cs.collected_carrots = 0;
  cs.gameStart = 0;
  cs.animation = 0;

  bunny.currCorrd.row = 134;
  bunny.currCorrd.col = 4;
  potentialBunny.currCorrd.row = 134;
  potentialBunny.currCorrd.col = 4;
  animationBunny.currCorrd.row = 91;
  animationBunny.currCorrd.col = 28;
  animationBunny.faceingRight = 1;
  animationBunny.moving = 0;
  animationBunny.length = 31;

  for (int i = 0; i < 24; i++) {
    bush[i].length = 10;
    bush[i].topLeftCorrd.col = bushCoordinates[i].col;
    bush[i].topLeftCorrd.row = bushCoordinates[i].row;
    bush[i].bottomRightCorrd.row = bush[i].topLeftCorrd.row + bush[i].length;
    bush[i].bottomRightCorrd.col = bush[i].topLeftCorrd.col + bush[i].length;
  }

  addCarrots(1, 8);
  u32 sec= -1;
  char timerStr[3];
  int timeleft = 45;
  int framecount = 0;


  
  

  while (1) {

    previousButtons = currentButtons;
    currentButtons = BUTTONS; // Load the current state of the buttons
    //Setting a Timer
    if (REG_TM3D != sec && cs.gameStart) {
      sec = REG_TM3D;
      waitForVBlank();
      undrawImageDMA(2, 155, 22, 10, Board);
      sprintf(timerStr, "%02d", timeleft - sec%60);  // Convert ticks to seconds
      drawString(2, 155, timerStr, ROSE);
      if (strcmp(timerStr, "00") == 0) {
        cs.gameStart = 0;
        REG_TM2CNT ^= TM_ENABLE; //Disable Timer
        cs.gamestate = TIMEOUTDRAW;
      }
    } else if (cs.animation) {
      framecount = framecount + 1;
    }

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    switch (cs.gamestate) {
      case DRAWSTART:
        waitForVBlank();
        drawFullScreenImageDMA(Start);
        cs.gamestate = START;
        cs.animation = 1;
        break;

      case START:
        waitForVBlank();
        if (framecount == 17) {
          framecount = 0;
          undrawImageDMA(animationBunny.currCorrd.row, animationBunny.currCorrd.col, animationBunny.length, animationBunny.length, Start);
          if (animationBunny.faceingRight) {
            if (animationBunny.currCorrd.col < 193) {
              animationBunny.currCorrd.col = animationBunny.currCorrd.col + 7;
              if (animationBunny.moving) {
                animationBunny.currCorrd.row = animationBunny.currCorrd.row + 7;
                drawImageDMA(animationBunny.currCorrd.row, animationBunny.currCorrd.col, animationBunny.length, animationBunny.length, sitRight);
                animationBunny.moving = 0;
              } else {
                animationBunny.currCorrd.row = animationBunny.currCorrd.row - 7;
                drawImageDMA(animationBunny.currCorrd.row, animationBunny.currCorrd.col, animationBunny.length, animationBunny.length, movingRight);
                animationBunny.moving = 1;
              }
            } else {
              if (animationBunny.moving) {
                animationBunny.currCorrd.row = animationBunny.currCorrd.row + 7;
                drawImageDMA(animationBunny.currCorrd.row, animationBunny.currCorrd.col, animationBunny.length, animationBunny.length, sitLeft);
                animationBunny.moving = 0;
                animationBunny.faceingRight = 0;
              } else
              {
                animationBunny.currCorrd.row = animationBunny.currCorrd.row - 7;
                drawImageDMA(animationBunny.currCorrd.row, animationBunny.currCorrd.col, animationBunny.length, animationBunny.length, movingLeft);
                animationBunny.moving = 1;
                animationBunny.faceingRight = 0;
              }
            }
          } else if (animationBunny.currCorrd.col > 20) {
            animationBunny.currCorrd.col = animationBunny.currCorrd.col - 7;
            if (animationBunny.moving) {
              animationBunny.currCorrd.row = animationBunny.currCorrd.row + 7;
              drawImageDMA(animationBunny.currCorrd.row, animationBunny.currCorrd.col, animationBunny.length, animationBunny.length, sitLeft);
              animationBunny.moving = 0;
            } else {
              animationBunny.currCorrd.row = animationBunny.currCorrd.row - 7;
              drawImageDMA(animationBunny.currCorrd.row, animationBunny.currCorrd.col, animationBunny.length, animationBunny.length, movingLeft);
              animationBunny.moving = 1;
            }
          } else {
            if (animationBunny.moving) {
              animationBunny.currCorrd.row = animationBunny.currCorrd.row + 7;
              drawImageDMA(animationBunny.currCorrd.row, animationBunny.currCorrd.col, animationBunny.length, animationBunny.length, sitRight);
              animationBunny.moving = 0;
              animationBunny.faceingRight = 1;
            } else {
              animationBunny.currCorrd.row = animationBunny.currCorrd.row - 7;
              drawImageDMA(animationBunny.currCorrd.row, animationBunny.currCorrd.col, animationBunny.length, animationBunny.length, movingRight);
              animationBunny.moving = 1;
              animationBunny.faceingRight = 1;
            }
          }
        }

        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          setupTimer();
          REG_TM2CNT ^= TM_ENABLE;
          REG_TM3D = 0; 
          REG_TM3CNT = 0; 
          REG_TM3CNT = TM_ENABLE | TM_CASCADE;
          cs.gameStart = 1;
          cs.gamestate = DRAWPLAY;
          cs.animation = 0;
        }
        break;
      
      case DRAWPLAY:
        waitForVBlank();
        drawFullScreenImageDMA(Board);
        drawImageDMA(bunny.currCorrd.row, bunny.currCorrd.col, BUNNYRIGHT_WIDTH, BUNNYRIGHT_HEIGHT, BunnyRight);
        for (int i = 0; i < 24; i++) {
          int color = randint(0,5);
          drawRectDMA(bush[i].topLeftCorrd.row, bush[i].topLeftCorrd.col, bush[i].length, bush[i].length, colors[color]);
        }
        for (int i = 0; i < 8; i++) {
          drawImageDMA(carrots[i].topLeftCorrd.row, carrots[i].topLeftCorrd.col, carrots[i].length, carrots[i].length, Carrot);
          carrots[i].removed = 0;
        }
        sprintf(cs.collectedcarrotsNum, "%d", cs.collected_carrots);
        drawString (2,40,cs.collectedcarrotsNum,ORANGE);
        drawString (2,4,"SCORE:",BUSHGREEN);
        drawString (2,94,"TIME LEFT:",BUSHGREEN);
        drawString(2, 155, timerStr, ROSE);
        cs.gamestate = PLAY;
        break;
      
      case PLAY:
        if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
          potentialBunny.currCorrd.row = potentialBunny.currCorrd.row - 11;
          setInnerPoints(&potentialBunny);
          int touchingObstacle = touchObstacle(&bush[0], &potentialBunny);

          if (bunny.currCorrd.row > 13 && !touchingObstacle) {
            bunny.prevCorrd.row = bunny.currCorrd.row;
            bunny.prevCorrd.col = bunny.currCorrd.col;
            bunny.currCorrd.row = bunny.currCorrd.row - 11;
            potentialBunny.currCorrd.row = bunny.currCorrd.row;
            potentialBunny.currCorrd.col = bunny.currCorrd.col;
            int touchingCarrot = touchCarrot(&carrots[0],&potentialBunny);
            if(touchingCarrot) {
              cs.collected_carrots = cs.collected_carrots + touchingCarrot;
              sprintf(cs.collectedcarrotsNum, "%d", cs.collected_carrots);
              cs.numcarrotsonBoard = cs.numcarrotsonBoard - touchingCarrot;
            }
            cs.gamestate = DRAWBUNNY;
          } 

        } else if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
          potentialBunny.currCorrd.row = potentialBunny.currCorrd.row + 11;
          setInnerPoints(&potentialBunny);
          int touchingObstacle = touchObstacle(&bush[0], &potentialBunny);

          if (bunny.currCorrd.row < 134 && !touchingObstacle) {
            bunny.prevCorrd.row = bunny.currCorrd.row;
            bunny.prevCorrd.col = bunny.currCorrd.col;
            bunny.currCorrd.row = bunny.currCorrd.row + 11;
            potentialBunny.currCorrd.row = bunny.currCorrd.row;
            potentialBunny.currCorrd.col = bunny.currCorrd.col;
            int touchingCarrot = touchCarrot(&carrots[0],&potentialBunny);
            if(touchingCarrot) {
              cs.collected_carrots = cs.collected_carrots + touchingCarrot;
              sprintf(cs.collectedcarrotsNum, "%d", cs.collected_carrots);
              cs.numcarrotsonBoard = cs.numcarrotsonBoard - touchingCarrot;
            }
            cs.gamestate = DRAWBUNNY;
          }

        } else if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
          potentialBunny.currCorrd.col = potentialBunny.currCorrd.col - 11;
          setInnerPoints(&potentialBunny);
          int touchingObstacle = touchObstacle(&bush[0], &potentialBunny);

          if (bunny.currCorrd.col > 4 && !touchingObstacle) {
            bunny.prevCorrd.row = bunny.currCorrd.row;
            bunny.prevCorrd.col = bunny.currCorrd.col;
            bunny.currCorrd.col = bunny.currCorrd.col - 11;
            potentialBunny.currCorrd.row = bunny.currCorrd.row;
            potentialBunny.currCorrd.col = bunny.currCorrd.col;
            int touchingCarrot = touchCarrot(&carrots[0],&potentialBunny);
            if(touchingCarrot) {
              cs.collected_carrots = cs.collected_carrots + touchingCarrot;
              sprintf(cs.collectedcarrotsNum, "%d", cs.collected_carrots);
              cs.numcarrotsonBoard = cs.numcarrotsonBoard - touchingCarrot;
            }
            cs.gamestate = DRAWBUNNY;
          }

        } else if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
          potentialBunny.currCorrd.col = potentialBunny.currCorrd.col + 11;
          setInnerPoints(&potentialBunny);
          int touchingObstacle = touchObstacle(&bush[0], &potentialBunny);


          if (bunny.currCorrd.col < 213 && !touchingObstacle) {
            bunny.prevCorrd.row = bunny.currCorrd.row;
            bunny.prevCorrd.col = bunny.currCorrd.col;
            bunny.currCorrd.col = bunny.currCorrd.col + 11;
            potentialBunny.currCorrd.row = bunny.currCorrd.row;
            potentialBunny.currCorrd.col = bunny.currCorrd.col;
            int touchingCarrot = touchCarrot(&carrots[0],&potentialBunny);
            if(touchingCarrot) {
              cs.collected_carrots = cs.collected_carrots + touchingCarrot;
              sprintf(cs.collectedcarrotsNum, "%d", cs.collected_carrots);
              cs.numcarrotsonBoard = cs.numcarrotsonBoard - touchingCarrot;
            }
            cs.gamestate = DRAWBUNNY;
          }
        } else if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          cs.gameStart = 0;
          cs.gamestate = RESTART;
          break;
        }
        potentialBunny.currCorrd.row = bunny.currCorrd.row;
        potentialBunny.currCorrd.col = bunny.currCorrd.col;
        break;

      case DRAWBUNNY:
        waitForVBlank();
        undrawImageDMA(bunny.prevCorrd.row, bunny.prevCorrd.col, BUNNYRIGHT_WIDTH, BUNNYRIGHT_HEIGHT, Board);
        drawImageDMA(bunny.currCorrd.row, bunny.currCorrd.col, BUNNYRIGHT_WIDTH, BUNNYRIGHT_HEIGHT, BunnyRight);
        undrawImageDMA(0,40, 14, 12, Board);
        drawString (2,40,cs.collectedcarrotsNum,ORANGE);
        cs.gamestate = DRAWCARROT;
        break;
  
      case DRAWCARROT:
        addCarrots(0, 8);
        waitForVBlank();
        for (int i = 0; i < 8; i++) {
          if (carrots[i].removed) {
            drawImageDMA(carrots[i].topLeftCorrd.row, carrots[i].topLeftCorrd.col, carrots[i].length, carrots[i].length, Carrot);
            carrots[i].removed = 0;
          }
        }
        
        cs.gamestate = PLAY;
        break;

      case RESTART:
        cs.gamestate = DRAWSTART;
        cs.numcarrotsonBoard = 0;
        cs.collected_carrots = 0;
        sprintf(cs.collectedcarrotsNum, "%d", cs.collected_carrots);
        bunny.currCorrd.row = 134;
        bunny.currCorrd.col = 4;
        potentialBunny.currCorrd.row = 134;
        potentialBunny.currCorrd.col = 4;
        addCarrots(1, 8);
        break;
      
      case TIMEOUTDRAW:
        waitForVBlank();
        drawFullScreenImageDMA(Time);
        cs.gamestate = TIMEOUT;
        drawCenteredString(69,61,10*11,3*11,"You Collected",BUSHGREEN);
        drawString (91,107,cs.collectedcarrotsNum,RUSTRED);
        drawCenteredString(91,64,10*11,3*11,"CARROTS",ORANGE);
        break;
      case TIMEOUT:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          cs.gamestate = RESTART;
          break;
        }
      
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
void addCarrots(int start, int carrotCount) {

  for (int i = 0; i < 8; i++) {
    if (carrots[i].removed || start) {
      while (cs.numcarrotsonBoard < 8) {
        int randRowMult = randint(0,12);
        int randColMult = randint(0,20);
    
        carrots[i].topLeftCorrd.row = 13 + (11 * randRowMult);
        carrots[i].topLeftCorrd.col = 5 + (11 * randColMult);
        int spaceocuupied;

        spaceocuupied = spaceOccupied(&bush[0], &carrots[i], &carrots[0], carrotCount, i);
      
        
    
        if (!spaceocuupied) {
          carrots[i].length = 10;
          carrots[i].bottomRightCorrd.row = carrots[i].topLeftCorrd.row 
            + carrots[i].length;
          carrots[i].bottomRightCorrd.col = carrots[i].topLeftCorrd.col 
            + carrots[i].length;
          cs.numcarrotsonBoard = cs.numcarrotsonBoard + 1;
          break;
        } else {
          carrots[i].topLeftCorrd.row = 0;
          carrots[i].topLeftCorrd.col = 0;
        }
        
      }
    }

  }
}

